# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: email_msg.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='email_msg.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0f\x65mail_msg.proto\"\x8a\x01\n\x10SendEmailRequest\x12\n\n\x02to\x18\x01 \x01(\t\x12\x0f\n\x07subject\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12\x0c\n\x04\x66rom\x18\x04 \x01(\t\x12\x0b\n\x03\x62\x63\x63\x18\x05 \x01(\t\x12\n\n\x02\x63\x63\x18\x06 \x01(\t\"!\n\x0b\x43ontentType\x12\x08\n\x04TEXT\x10\x00\x12\x08\n\x04HTML\x10\x01\"$\n\x11SendEmailResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2=\n\x05\x45mail\x12\x34\n\tSendEmail\x12\x11.SendEmailRequest\x1a\x12.SendEmailResponse\"\x00\x62\x06proto3'
)



_SENDEMAILREQUEST_CONTENTTYPE = _descriptor.EnumDescriptor(
  name='ContentType',
  full_name='SendEmailRequest.ContentType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TEXT', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='HTML', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=125,
  serialized_end=158,
)
_sym_db.RegisterEnumDescriptor(_SENDEMAILREQUEST_CONTENTTYPE)


_SENDEMAILREQUEST = _descriptor.Descriptor(
  name='SendEmailRequest',
  full_name='SendEmailRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='to', full_name='SendEmailRequest.to', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='subject', full_name='SendEmailRequest.subject', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='content', full_name='SendEmailRequest.content', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='from', full_name='SendEmailRequest.from', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bcc', full_name='SendEmailRequest.bcc', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cc', full_name='SendEmailRequest.cc', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SENDEMAILREQUEST_CONTENTTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=158,
)


_SENDEMAILRESPONSE = _descriptor.Descriptor(
  name='SendEmailResponse',
  full_name='SendEmailResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='SendEmailResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=160,
  serialized_end=196,
)

_SENDEMAILREQUEST_CONTENTTYPE.containing_type = _SENDEMAILREQUEST
DESCRIPTOR.message_types_by_name['SendEmailRequest'] = _SENDEMAILREQUEST
DESCRIPTOR.message_types_by_name['SendEmailResponse'] = _SENDEMAILRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SendEmailRequest = _reflection.GeneratedProtocolMessageType('SendEmailRequest', (_message.Message,), {
  'DESCRIPTOR' : _SENDEMAILREQUEST,
  '__module__' : 'email_msg_pb2'
  # @@protoc_insertion_point(class_scope:SendEmailRequest)
  })
_sym_db.RegisterMessage(SendEmailRequest)

SendEmailResponse = _reflection.GeneratedProtocolMessageType('SendEmailResponse', (_message.Message,), {
  'DESCRIPTOR' : _SENDEMAILRESPONSE,
  '__module__' : 'email_msg_pb2'
  # @@protoc_insertion_point(class_scope:SendEmailResponse)
  })
_sym_db.RegisterMessage(SendEmailResponse)



_EMAIL = _descriptor.ServiceDescriptor(
  name='Email',
  full_name='Email',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=198,
  serialized_end=259,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendEmail',
    full_name='Email.SendEmail',
    index=0,
    containing_service=None,
    input_type=_SENDEMAILREQUEST,
    output_type=_SENDEMAILRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_EMAIL)

DESCRIPTOR.services_by_name['Email'] = _EMAIL

# @@protoc_insertion_point(module_scope)
